### ISSUE TITLE
Modded block variants not harvestable

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Harvester#10]
Hello,
I am having an issue with modded blocks with variants, specifically those from Conquest Reforged.
the items in question are Tin Ore and Bronze Ore
they share a name "conquest:stone_full_hard2" but they are variants of one another.

How would i set this up? I cannot even get them breakable at the moment.
within Itemizer i have added the line: "Tin" : "conquest:stone_full_hard2"
but that does not seem to function.

If it helps the NBT data of the two blocks are listed as variant 9 and variant 10

**Comment by hellbringer616** [comment]
Okay.. i stand corrected; I had it working but it would respawn to the default variant, now that i have the variants constrained i once again cannot harvest them :(

harvestables.conf:
```
harvestables = [
  {
    type: "minecraft:coal_ore",
    respawnmin: 2,
    respawnmax: 5
  },
  {
    type: "conquest:stone_full_hard2",
    state {
      variant { value = "tin ore" }
    },
    respawnmin: 2,
    respawnmax: 5
  },
  {
    type: "conquest:stone_full_hard2",
    state {
      variant { value = "copper ore" }
    },
    respawnmin: 2,
    respawnmax: 5
  }
]
```

drops.conf:

```
default = [
  "minecraft:coal_ore",
  "minecraft:iron_ore",
  "minecraft:gold_ore",
  "minecraft:diamond_ore",
  "minecraft:wood",
  "conquest:stone_full_hard2"
]
```

**Comment by raiponz** [comment]
Hi,
It work better than I expected. which version of forgeServer and spongeforge do you use?

**Comment by raiponz** [comment]
I think your block state is wrong , use this list to set correct block state https://io.conquestreforged.com/idlist/ unfortunatly is not up to date with lastest block.

**Comment by hellbringer616** [comment]
Worked like a charm!
thank you so much :D

For anyone else who stumbles upon this; Conquest uses the Nato Phonetic alphabet for their varients
NBT 0 = alpha
NBT 1 = bravo
NBT 3 = charlie
NBT 4 = delta

etc etc

mine being 9 and 10 were juliet and kilo respectively
