### ISSUE TITLE
Bonemeal doing nothing. Grass not growing.

### ISSUE THREAD

**Issue by lejonny** [OnapleRPG/Harvester#11]
Grass is not growing and bonemeal does nothing on grass or saplings. Trees do not grow on their own neither wheat or other plants.

I tested if any other plugin does this, but as soon as i remove the harvester plugin everything is working again.

**Comment by hellbringer616** [comment]
Can confirm this happens for me as well; I was wondering why it didn't work!

**Comment by zessirb** [comment]
I am sorry we did not address the issue earlier. 
This was indeed a mistake we made. Harvester has the possibility to disable block growth, but we should not have set it by default, and we did not even update the documentation accordingly. 
 
The created PR will set the behavior to allow block growth unless specified in configuration, as well as update the Readme file.  
Sorry for the inconvenience.
