### ISSUE TITLE
[REQUEST] Default drop plus defined drop

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Harvester#12]
If part is defined in `default` and in `harvest_items` on break event drop both the default item and the defined `harvest item`

Example: 
```
default = [
   	"minecraft:obsidian",
]
harvest_items = [
   {
       type: "minecraft:obsidian",
       item_name: "minecraft:cobblestone",
       item_ref: 2,
       pool_ref: 1
   }
]
```
would drop the default obsidian block, a cobblestone block, Item_ref 2 from Itemizer, and attempt to get an item from pool 1 of itemizer.

**Comment by zessirb** [comment]
It makes sense to keep the default behavior as well as the harvester one, indeed.  
@Hbeau I recall that  the "default" blocks cancel the custom event hook, so maybe we will have to call the Harvester function anyway with a boolean setting "drop default block" to true.

**Comment by zessirb** [comment]
This is not supported with the [1.2.0 version](https://github.com/OnapleRPG/Harvester/releases/download/1.2.0/Harvester.jar).  
When you have an item that is matched by the "harvest_items" and the "default" array, it will both drop its default drop and the configured item type and/or itemizer item and/or itemizer pool result.
