### ISSUE TITLE
Extend the drop system to mob

### ISSUE THREAD

**Issue by Hbeau** [OnapleRPG/Harvester#4]
Use the harvester drop system already in place for block to manage monster loot. I see several advantages to this choice (insted of use two systems with brawlator).
 * Monster and block drop are bind to the same event. 
* the code for each fonction is almost the same 
* drop management is in the responsability of harvester
* easier to add new features

**Comment by hellbringer616** [comment]
Is this covered by [Brawlator](https://github.com/OnapleRPG/Brawlator)?
I would personally love to be able to define a mob type so random spawned mobs can in fact have drops as well as these custom ones.

**Comment by Hbeau** [comment]
You right , this should be covered by brawlator. This issue is no longer relevant.
