### ISSUE TITLE
[REQUEST] Permission to bypass Harvester

### ISSUE THREAD

**Issue by hellbringer616** [OnapleRPG/Harvester#9]
I'd like a permission i could set to allow any blocks to be broken (bypass Harvester)
this is for those on the server who will be building the actual world.

**Comment by raiponz** [comment]
Hello,
It's a good idea and that might to be easy to develop 😄. 

By now you can bypass harvester if you are in creative mode.

**Comment by hellbringer616** [comment]
Unfortunately being in creative mode does no allow this plugin to be bypassed.. so i can't use it :(

very interested once it can however!

**Comment by raiponz** [comment]
It's look like this feature was removed. I have fixed that

**Comment by hellbringer616** [comment]
Looking very much forward to this upcoming version then!
